baseURL: https://nohad-mortada.netlify.app/
languageCode: en-us
title: Nohad Mortada's Portfolio Website
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: Welcome to my page, where you can find my short story, my resume, and a glimpse of my coding art, photos of my dog, and a blog about my beloved country
    
   
    title: Hello i am Nohad, an MFA student at London Business School.
  blog: {}
  contact:
    address:
      - city: London, W8 4QN 
        country: UK
        street: Kensington Palace Gardens
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: nmortada.mfa2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (44) 7852870771 
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Company Name
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
     #- icon: fa-twitter
     #   label: Twitter
      #  url: https://www.twitter.com
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/nohad.mortada
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/nohadmortada/?hl=en
      - icon: fa-github
        label: GitHub
        url: https://github.com/nohadmortada
      - icon: fa-linkedin
        label: LinkedIn
        url: www.linkedin.com/in/nohadmortada
  image: 'lbs.jpg'
  name: Nohad Mortada
  navigation:
    button1:
      - name: Get Started
        url:  blogs
    button2:
      - name: Log in
        url: '#'
    links:
      - name: menu
        url: '#'
      - name: Blogs
        url: blogs
      - \#name: Nohad's resume
        \#url: https://docs.google.com/document/d/1FIFqwkcLYTmWnfe9ivVw-EdcOHuAreS0JPv398W78lg/edit?usp=sharing
      - \# name: Elements
        \# url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: Story.jpg 
        subtitle: Cool photo of myself and a short story
        title: Nohad's life 
        url: blogs/ipsum
      - image: Resume.jpg 
        subtitle: Ambitious student looking to break into investment banking 
        title: My resume 
        url: blogs/CV 
      - image: germany.jpg 
        subtitle: Analysed People's drinking habits, Financial Stocks, Covid Vaccinations, and Opinion polls for the 2021 German elections 
        title: Data Analytics for Finance Homework 1 
        url: blogs/homework1_website 
      - image: Climatt.jpg 
        subtitle: Analysed Climate change and temperature anomalies, Global Warming and US Presidency
        title: Data Analytics for Finance Homework 2 
        url: blogs/homework2_website 
      - image: Tyson 1.jpg
        subtitle: Some Photos of my Pitbull
        title: Tyson the Dog
        url: blogs/Tyson
      - image: Leb.jpg
        subtitle: A glimpse of my beautiful country in pain
        title: Lebanon
        url: blogs/magna
  two:
    buttonText: Get Started
    enable: yes
    subtitle: Please find below my contact information. Don't hesitate to contact me or reach out via social media!
    title: !
    url: blogs
