baseURL: https://nohad-mortada.netlify.app/
languageCode: en-us
title: Nohad Mortada's Portfolio Website
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: Welcome everyone to my Website
    
   
    title: Hello i am Nohad, an MFA student at London Business School.
  blog: {}
  contact:
    address:
      - city: London, W8 4QN 
        country: UK
        street: Kensington Palace Gardens
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: nmortada.mfa2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (44) 7852870771 
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Company Name
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
    #  - icon: fa-twitter
     #   label: Twitter
      #  url: https://www.twitter.com
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/nohad.mortada
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/nohadmortada/?hl=en
      - icon: fa-github
        label: GitHub
        url: https://github.com/nohadmortada
      - icon: fa-linkedin
        label: LinkedIn
        url: www.linkedin.com/in/nohadmortada
  image: 'lbs.jpg'
  name: Nohad Mortada
  navigation:
    button1:
      - name: My Resume
        url: https://www.mergersandinquisitions.com/sales-trading/
    button2:
      - name: Log in
        url: '#'
    links:
      - name: menu
        url: '#'
      - name: Blogs
        url: blogs
      - \# name: Nohad's resume
        \# url: file:///Users/nohadmessimortada/Desktop/IB%20Applications/CV%20NOHAD%20MORTADA.pdf
      - \# name: Elements
        \# url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: lbs.jpg
        subtitle: Ipsum Dolor Sit Amet
        title: Individual Assignment
        url: https://stackoverflow.com/questions/34998819/r-code-how-to-generate-variable-based-on-multiple-conditions-from-other-variabl
      - image: pic02.jpg
        subtitle: Feugiat Amet Tempus
        title: Tempus
        url: blogs/tempus
      - image: pic03.jpg
        subtitle: Lorem Etiam Nullam
        title: Magna
        url: blogs/magna
      - image: pic04.jpg
        subtitle: Nisl Sed Aliquam
        title: Ipsum
        url: blogs/ipsum
      - image: pic05.jpg
        subtitle: Ipsum Dolor Sit Amet
        title: Consequat
        url: blogs/ipsum
      - image: pic06.jpg
        subtitle: Feugiat Amet Tempus
        title: Etiam
        url: blogs/ipsum
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
      \n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \n    Pellentesque
      condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
      pellentesque lorem ipsum dolor. \n    Nullam et orci eu lorem consequat tincidunt.
      Vivamus et sagittis libero.\n    Mauris aliquet magna magna sed nunc rhoncus
      amet pharetra et feugiat tempus."
    title: Massa libero
    url: blogs
