---
categories:  
- ""    #the front matter should be like the one found in, e.g., blog2.md. It cannot be like the normal Rmd we used
- ""
date: "2021-09-30"
description: Analysed Climate change and temperature anomalies and Global Warming and Political Views # the title that will show up once someone gets to this page
draft: false
image: America.jpg  # save picture in \static\img\blogs. Acceptable formats= jpg, jpeg, or png . Your iPhone pics wont work

keywords: ""
slug: homework2_website # slug is the shorthand URL address... no spaces plz
title: Data Analytics for Finance Homework 2
---

<script src="/rmarkdown-libs/header-attrs/header-attrs.js"></script>


<div id="climate-change-and-temperature-anomalies" class="section level1">
<h1>Climate change and temperature anomalies</h1>
<p>If we wanted to study climate change, we can find data on the <em>Combined Land-Surface Air and Sea-Surface Water Temperature Anomalies</em> in the Northern Hemisphere at <a href="https://data.giss.nasa.gov/gistemp">NASA’s Goddard Institute for Space Studies</a>. The <a href="https://data.giss.nasa.gov/gistemp/tabledata_v4/NH.Ts+dSST.txt">tabular data of temperature anomalies can be found here</a></p>
<p>To define temperature anomalies you need to have a reference, or base, period which NASA clearly states that it is the period between 1951-1980.</p>
<p>Run the code below to load the file:</p>
<pre class="r"><code>weather &lt;- 
  read_csv(&quot;https://data.giss.nasa.gov/gistemp/tabledata_v4/NH.Ts+dSST.csv&quot;, 
           skip = 1, 
           na = &quot;***&quot;)</code></pre>
<p>Notice that, when using this function, we added two options: <code>skip</code> and <code>na</code>.</p>
<ol style="list-style-type: decimal">
<li>The <code>skip=1</code> option is there as the real data table only starts in Row 2, so we need to skip one row.</li>
<li><code>na = "***"</code> option informs R how missing observations in the spreadsheet are coded. When looking at the spreadsheet, you can see that missing data is coded as “***”. It is best to specify this here, as otherwise some of the data is not recognized as numeric data.</li>
</ol>
<p>Once the data is loaded, notice that there is a object titled <code>weather</code> in the <code>Environment</code> panel. If you cannot see the panel (usually on the top-right), go to <code>Tools</code> &gt; <code>Global Options</code> &gt; <code>Pane Layout</code> and tick the checkbox next to <code>Environment</code>. Click on the <code>weather</code> object, and the dataframe will pop up on a seperate tab. Inspect the dataframe.</p>
<p>For each month and year, the dataframe shows the deviation of temperature from the normal (expected). Further the dataframe is in wide format.</p>
<p>You have two objectives in this section:</p>
<ol style="list-style-type: decimal">
<li><p>Select the year and the twelve month variables from the <code>weather</code> dataset. We do not need the others (J-D, D-N, DJF, etc.) for this assignment. Hint: use <code>select()</code> function.</p></li>
<li><p>Convert the dataframe from wide to ‘long’ format. Hint: use <code>gather()</code> or <code>pivot_longer()</code> function. Name the new dataframe as <code>tidyweather</code>, name the variable containing the name of the month as <code>month</code>, and the temperature deviation values as <code>delta</code>.</p></li>
</ol>
<pre class="r"><code>tidyweather&lt;-weather%&gt;%
pivot_longer(cols = c(2:13), #columns 3 to 5
               names_to = &quot;Month&quot;,
               values_to = &quot;delta&quot;)%&gt;%
select(c(&quot;Year&quot;, &quot;Month&quot;, &quot;delta&quot;))
head(tidyweather)</code></pre>
<pre><code>## # A tibble: 6 × 3
##    Year Month delta
##   &lt;dbl&gt; &lt;chr&gt; &lt;dbl&gt;
## 1  1880 Jan   -0.35
## 2  1880 Feb   -0.51
## 3  1880 Mar   -0.23
## 4  1880 Apr   -0.3 
## 5  1880 May   -0.06
## 6  1880 Jun   -0.16</code></pre>
<p>Inspect your dataframe. It should have three variables now, one each for</p>
<ol style="list-style-type: decimal">
<li>year,</li>
<li>month, and</li>
<li>delta, or temperature deviation.</li>
</ol>
<div id="plotting-information" class="section level2">
<h2>Plotting Information</h2>
<p>Let us plot the data using a time-series scatter plot, and add a trendline. To do that, we first need to create a new variable called <code>date</code> in order to ensure that the <code>delta</code> values are plot chronologically.</p>
<blockquote>
<p>In the following chunk of code, I used the <code>eval=FALSE</code> argument, which does not run a chunk of code; I did so that you can knit the document before tidying the data and creating a new dataframe <code>tidyweather</code>. When you actually want to run this code and knit your document, you must delete <code>eval=FALSE</code>, <strong>not just here but in all chunks were <code>eval=FALSE</code> appears.</strong></p>
</blockquote>
<pre class="r"><code>tidyweather &lt;- tidyweather %&gt;%
  mutate(date = ymd(paste(as.character(Year), Month, &quot;1&quot;)),
         Month = month(date, label=TRUE),
         year = year(date))

ggplot(tidyweather, aes(x=date, y = delta))+
  geom_point()+
  geom_smooth(color=&quot;red&quot;) +
  theme_bw() +
  labs (
    title = &quot;Weather Anomalies&quot;
  )</code></pre>
<p>Is the effect of increasing temperature more pronounced in some months? Use <code>facet_wrap()</code> to produce a seperate scatter plot for each month, again with a smoothing line. Your chart should human-readable labels; that is, each month should be labeled “Jan”, “Feb”, “Mar” (full or abbreviated month names are fine), not <code>1</code>, <code>2</code>, <code>3</code>.</p>
<p><img src="/blogs/homework2_website_files/figure-html/facet_wrap-1.png" width="648" style="display: block; margin: auto;" /></p>
<p>It is sometimes useful to group data into different time periods to study historical data. For example, we often refer to decades such as 1970s, 1980s, 1990s etc. to refer to a period of time. NASA calcuialtes a temperature anomaly, as difference form the base periof of 1951-1980. The code below creates a new data frame called <code>comparison</code> that groups data in five time periods: 1881-1920, 1921-1950, 1951-1980, 1981-2010 and 2011-present.</p>
<p>We remove data before 1800 and before using <code>filter</code>. Then, we use the <code>mutate</code> function to create a new variable <code>interval</code> which contains information on which period each observation belongs to. We can assign the different periods using <code>case_when()</code>.</p>
<pre class="r"><code>comparison &lt;- tidyweather %&gt;% 
  filter(Year&gt;= 1881) %&gt;%     #remove years prior to 1881
  #create new variable &#39;interval&#39;, and assign values based on criteria below:
  mutate(interval = case_when(
    Year %in% c(1881:1920) ~ &quot;1881-1920&quot;,
    Year %in% c(1921:1950) ~ &quot;1921-1950&quot;,
    Year %in% c(1951:1980) ~ &quot;1951-1980&quot;,
    Year %in% c(1981:2010) ~ &quot;1981-2010&quot;,
    TRUE ~ &quot;2011-present&quot;
  ))</code></pre>
<p>Inspect the <code>comparison</code> dataframe by clicking on it in the <code>Environment</code> pane.</p>
<p>Now that we have the <code>interval</code> variable, we can create a density plot to study the distribution of monthly deviations (<code>delta</code>), grouped by the different time periods we are interested in. Set <code>fill</code> to <code>interval</code> to group and colour the data by different time periods.</p>
<pre class="r"><code>ggplot(comparison, aes(x=delta, fill=interval))+
  geom_density(alpha=0.2) +   #density plot with tranparency set to 20%
  theme_bw() +                #theme
  labs (
    title = &quot;Density Plot for Monthly Temperature Anomalies&quot;,
    y     = &quot;Density&quot;         #changing y-axis label to sentence case
  )</code></pre>
<p>So far, we have been working with monthly anomalies. However, we might be interested in average annual anomalies. We can do this by using <code>group_by()</code> and <code>summarise()</code>, followed by a scatter plot to display the result.</p>
<pre class="r"><code>#creating yearly averages
average_annual_anomaly &lt;- tidyweather %&gt;% 
  group_by(Year) %&gt;%   #grouping data by Year
  
  # creating summaries for mean delta 
  # use `na.rm=TRUE` to eliminate NA (not available) values 
  summarise(annual_average_delta =  mean(delta,na.rm=TRUE))
    
#plotting the data:
ggplot(average_annual_anomaly, aes(x=Year, y= annual_average_delta))+
  geom_point()+
  
  #Fit the best fit line, using LOESS method
  geom_smooth() +
  
  #change to theme_bw() to have white background + black frame around plot
  theme_bw() +
  labs (
    title = &quot;Average Yearly Anomaly&quot;,
    y     = &quot;Average Annual Delta&quot;
  )                         </code></pre>
</div>
<div id="confidence-interval-for-delta" class="section level2">
<h2>Confidence Interval for <code>delta</code></h2>
<p><a href="https://earthobservatory.nasa.gov/world-of-change/decadaltemp.php">NASA points out on their website</a> that</p>
<blockquote>
<p>A one-degree global change is significant because it takes a vast amount of heat to warm all the oceans, atmosphere, and land by that much. In the past, a one- to two-degree drop was all it took to plunge the Earth into the Little Ice Age.</p>
</blockquote>
<p>Your task is to construct a confidence interval for the average annual delta since 2011, both using a formula and using a bootstrap simulation with the <code>infer</code> package. Recall that the dataframe <code>comparison</code> has already grouped temperature anomalies according to time intervals; we are only interested in what is happening between 2011-present.</p>
<pre class="r"><code>formula_ci &lt;- comparison %&gt;% 

  
  # choose the interval 2011-present
  filter(Year&gt;=2011)%&gt;% 
  # what dplyr verb will you use? 
 # group_by(Year)%&gt;% 
  # calculate summary statistics for temperature deviation (delta)
  # calculate mean, SD, count, SE, lower/upper 95% CI
  # what dplyr verb will you use? 
  summarise(
    mean_delta = mean(delta,na.rm=TRUE),
    sd_delta = sd(delta,na.rm=TRUE),
    count = n(),
    se_delta = sd_delta/ sqrt(count),
    t_critical = qt(0.975, count - 1 ),
    lower = mean_delta - t_critical * se_delta,
    upper = mean_delta + t_critical * se_delta
  ) 

#print out formula_CI
formula_ci</code></pre>
<pre class="r"><code>library(infer)
# use the infer package to construct a 95% CI for delta
set.seed(1234)

comparison &lt;- tidyweather %&gt;% 
  filter(Year&gt;= 1881) %&gt;%     #remove years prior to 1881
  #create new variable &#39;interval&#39;, and assign values based on criteria below:
  mutate(interval = case_when(
    Year %in% c(1881:1920) ~ &quot;1881-1920&quot;,
    Year %in% c(1921:1950) ~ &quot;1921-1950&quot;,
    Year %in% c(1951:1980) ~ &quot;1951-1980&quot;,
    Year %in% c(1981:2010) ~ &quot;1981-2010&quot;,
    TRUE ~ &quot;2011-present&quot;
  ))

percentile_ci&lt;-comparison%&gt;%
  #get_confidence_interval(level=.95,type=&quot;percentile&quot;)
#generate(reps=10,type=)
  filter(Year&gt;=2011)%&gt;%
  group_by(Year)%&gt;% 
  specify(response = delta)%&gt;%
  generate(reps=1000,type=&quot;bootstrap&quot;)%&gt;%
  calculate(stat=&quot;mean&quot;)%&gt;%
  get_confidence_interval(level=.95,type=&quot;percentile&quot;)


percentile_ci</code></pre>
<pre><code>## # A tibble: 1 × 2
##   lower_ci upper_ci
##      &lt;dbl&gt;    &lt;dbl&gt;
## 1     1.01     1.11</code></pre>
<blockquote>
<p>What is the data showing us? Please type your answer after (and outside!) this blockquote. You have to explain what you have done, and the interpretation of the result. One paragraph max, please!</p>
</blockquote>
<p><strong>Looking at the past 10 years, we are 95% certain that the temperature variation will end up within 1.01 - 1.11 of the fixed unknown temperature. The interval changes slightly depending on the method used but we can conclude that 1.01/02 -1.11 is the likely change of the true uknown parameter (delta temperature). If in the first case we compute the confidence interval explicitly, in the second we use the bootstrap method that optimizes the computation for us simulating a sample of size 1000. Notice that the interval does not change if we select size 10000 meaning 1000 is optimal to get two decimal precision.</strong></p>
</div>
</div>
<div id="global-warming-and-political-views-gss" class="section level1">
<h1>Global warming and political views (GSS)</h1>
<p><a href="https://www.pewresearch.org/2010/10/27/wide-partisan-divide-over-global-warming/">A 2010 Pew Research poll</a> asked 1,306 Americans, “From what you’ve read and heard, is there solid evidence that the average temperature on earth has been getting warmer over the past few decades, or not?”</p>
<p>In this exercise we analyze whether there are any differences between the proportion of people who believe the earth is getting warmer and their political ideology. As usual, from the <strong>survey sample data</strong>, we will use the proportions to estimate values of <em>population parameters</em>. The file has 2253 observations on the following 2 variables:</p>
<ul>
<li><code>party_or_ideology</code>: a factor (categorical) variable with levels Conservative Republican, Liberal Democrat, Mod/Cons Democrat, Mod/Lib Republican</li>
<li><code>response</code> : whether the respondent believes the earth is warming or not, or Don’t know/ refuse to answer</li>
</ul>
<pre class="r"><code>#global_warming_pew &lt;- read_csv(here::here(&quot;data&quot;, &quot;global_warming_pew.csv&quot;))
global_warming_pew &lt;- read_csv(&quot;/Users/nohadmessimortada/Desktop/ca09.mfa2022/data/global_warming_pew.csv&quot;)</code></pre>
<p>You will also notice that many responses should not be taken into consideration, like “No Answer”, “Don’t Know”, “Not applicable”, “Refused to Answer”.</p>
<pre class="r"><code>global_warming_pew %&gt;% 
  count(party_or_ideology, response)</code></pre>
<pre><code>## # A tibble: 12 × 3
##    party_or_ideology       response                          n
##    &lt;chr&gt;                   &lt;chr&gt;                         &lt;int&gt;
##  1 Conservative Republican Don&#39;t know / refuse to answer    45
##  2 Conservative Republican Earth is warming                248
##  3 Conservative Republican Not warming                     450
##  4 Liberal Democrat        Don&#39;t know / refuse to answer    23
##  5 Liberal Democrat        Earth is warming                405
##  6 Liberal Democrat        Not warming                      23
##  7 Mod/Cons Democrat       Don&#39;t know / refuse to answer    45
##  8 Mod/Cons Democrat       Earth is warming                563
##  9 Mod/Cons Democrat       Not warming                     158
## 10 Mod/Lib Republican      Don&#39;t know / refuse to answer    23
## 11 Mod/Lib Republican      Earth is warming                135
## 12 Mod/Lib Republican      Not warming                     135</code></pre>
<p>We will be constructing three 95% confidence intervals to estimate population parameters, for the % who believe that <strong>Earth is warming</strong>, accoridng to their party or ideology. You can create the CIs using the formulas by hand, or use <code>prop.test()</code>– just rememebr to exclude the Dont know / refuse to answer!</p>
<pre class="r"><code>formula_ci &lt;- global_warming_pew %&gt;% filter(response != &quot;Don&#39;t know / refuse to answer&quot;) %&gt;%
  group_by(party_or_ideology)%&gt;%
summarise(
    mean_w =  mean(response == &quot;Earth is warming&quot;),
    sd_w = sd(response == &quot;Earth is warming&quot;),
    count = n(),
    se_w = sd_w/ sqrt(count),
    t_critical = qt(0.975, count - 1 ),
    lower = mean_w - t_critical * se_w,
    upper = mean_w + t_critical * se_w
  )

formula_ci</code></pre>
<pre><code>## # A tibble: 4 × 8
##   party_or_ideology       mean_w  sd_w count   se_w t_critical lower upper
##   &lt;chr&gt;                    &lt;dbl&gt; &lt;dbl&gt; &lt;int&gt;  &lt;dbl&gt;      &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1 Conservative Republican  0.355 0.479   698 0.0181       1.96 0.320 0.391
## 2 Liberal Democrat         0.946 0.226   428 0.0109       1.97 0.925 0.968
## 3 Mod/Cons Democrat        0.781 0.414   721 0.0154       1.96 0.751 0.811
## 4 Mod/Lib Republican       0.5   0.501   270 0.0305       1.97 0.440 0.560</code></pre>
<p>Does it appear that whether or not a respondent believes the earth is warming is independent of their party ideology? You may want to</p>
<pre class="r"><code>agree &lt;- global_warming_pew %&gt;% filter(response == &quot;Earth is warming&quot;)%&gt;%
  count(party_or_ideology, response)
agree&lt;-agree[,3]
colnames(agree)&lt;-&quot;count&quot;
total &lt;- formula_ci[,4]

t&lt;-cbind(agree,total)

prop.test(t[,1],t[,2])</code></pre>
<pre><code>## 
##  4-sample test for equality of proportions without continuity
##  correction
## 
## data:  [ out of [t out of t out of 1 out of 2
## X-squared = 504, df = 3, p-value &lt;2e-16
## alternative hypothesis: two.sided
## sample estimates:
## prop 1 prop 2 prop 3 prop 4 
##  0.355  0.946  0.781  0.500</code></pre>
<p><strong>No, as under 0.95 CI, p-value&lt;0.05,the respondent believes the earth is warming is related to their party ideology.”Liberal Democrat” and “Mod/Cons Democrat” are more likely to support the view of the earth is warming.</strong></p>
<p>You may want to read on <a href="https://www.brookings.edu/research/the-challenging-politics-of-climate-change/">The challenging politics of climate change</a></p>
</div>
<div id="bidens-approval-margins" class="section level1">
<h1>Biden’s Approval Margins</h1>
<p>As we saw in class, fivethirtyeight.com has detailed data on <a href="https://projects.fivethirtyeight.com/biden-approval-ratings">all polls that track the president’s approval</a></p>
<pre class="r"><code># Import approval polls data directly off fivethirtyeight website
approval_polllist &lt;- read_csv(&#39;https://projects.fivethirtyeight.com/biden-approval-data/approval_polllist.csv&#39;) 

glimpse(approval_polllist)</code></pre>
<pre><code>## Rows: 1,928
## Columns: 22
## $ president           &lt;chr&gt; &quot;Joseph R. Biden Jr.&quot;, &quot;Joseph R. Biden Jr.&quot;, &quot;Jos…
## $ subgroup            &lt;chr&gt; &quot;All polls&quot;, &quot;All polls&quot;, &quot;All polls&quot;, &quot;All polls&quot;…
## $ modeldate           &lt;chr&gt; &quot;10/19/2021&quot;, &quot;10/19/2021&quot;, &quot;10/19/2021&quot;, &quot;10/19/2…
## $ startdate           &lt;chr&gt; &quot;1/19/2021&quot;, &quot;1/19/2021&quot;, &quot;1/20/2021&quot;, &quot;1/20/2021&quot;…
## $ enddate             &lt;chr&gt; &quot;1/21/2021&quot;, &quot;1/21/2021&quot;, &quot;1/22/2021&quot;, &quot;1/21/2021&quot;…
## $ pollster            &lt;chr&gt; &quot;Rasmussen Reports/Pulse Opinion Research&quot;, &quot;Morni…
## $ grade               &lt;chr&gt; &quot;B&quot;, &quot;B&quot;, &quot;B&quot;, &quot;B-&quot;, &quot;B&quot;, &quot;B+&quot;, &quot;B+&quot;, &quot;B&quot;, &quot;B&quot;, &quot;B…
## $ samplesize          &lt;dbl&gt; 1500, 15000, 15000, 1115, 1993, 1516, 941, 15000, …
## $ population          &lt;chr&gt; &quot;lv&quot;, &quot;a&quot;, &quot;a&quot;, &quot;a&quot;, &quot;rv&quot;, &quot;a&quot;, &quot;rv&quot;, &quot;a&quot;, &quot;lv&quot;, &quot;…
## $ weight              &lt;dbl&gt; 0.3382, 0.2594, 0.2333, 1.1014, 0.0930, 1.2454, 1.…
## $ influence           &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
## $ approve             &lt;dbl&gt; 48, 50, 51, 55, 56, 45, 63, 52, 48, 58, 54, 55, 48…
## $ disapprove          &lt;dbl&gt; 45, 28, 28, 32, 31, 28, 37, 29, 47, 32, 30, 33, 47…
## $ adjusted_approve    &lt;dbl&gt; 50.5, 48.6, 49.6, 53.9, 54.6, 46.5, 58.7, 50.6, 50…
## $ adjusted_disapprove &lt;dbl&gt; 38.8, 31.2, 31.2, 33.0, 34.2, 28.4, 38.0, 32.2, 40…
## $ multiversions       &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
## $ tracking            &lt;lgl&gt; TRUE, TRUE, TRUE, NA, NA, NA, NA, TRUE, TRUE, NA, …
## $ url                 &lt;chr&gt; &quot;https://www.rasmussenreports.com/public_content/p…
## $ poll_id             &lt;dbl&gt; 74247, 74272, 74273, 74248, 74246, 74327, 74256, 7…
## $ question_id         &lt;dbl&gt; 139395, 139491, 139492, 139404, 139394, 139570, 13…
## $ createddate         &lt;chr&gt; &quot;1/22/2021&quot;, &quot;1/28/2021&quot;, &quot;1/28/2021&quot;, &quot;1/22/2021&quot;…
## $ timestamp           &lt;chr&gt; &quot;09:36:10 19 Oct 2021&quot;, &quot;09:36:10 19 Oct 2021&quot;, &quot;0…</code></pre>
<pre class="r"><code># Use `lubridate` to fix dates, as they are given as characters.
library(lubridate)
mydata1 &lt;- approval_polllist  %&gt;% 
  mutate(enddate1 = as.Date(enddate, format = &quot;%m/%d/%Y&quot;))</code></pre>
<div id="create-a-plot" class="section level2">
<h2>Create a plot</h2>
<p>What I would like you to do is to calculate the average net approval rate (approve- disapprove) for each week since he got into office. I want you plot the net approval, along with its 95% confidence interval. There are various dates given for each poll, please use <code>enddate</code>, i.e., the date the poll ended.</p>
<p>Also, please add an orange line at zero. Your plot should look like this:</p>
<p><img src="/Users/nohadmessimortada/Desktop/my_website/images/biden_approval_margin.png" width="100%" style="display: block; margin: auto;" /></p>
<pre class="r"><code>#calculate net approval rate (approve- disapprove) for each line
mydata2 &lt;- mydata1 %&gt;% 
  mutate(net_approval_rate = approve - disapprove) %&gt;% 
  
#get the week of the year
  mutate(week = week(enddate1)) %&gt;% 

#select columns we need
  select(c(&quot;net_approval_rate&quot;,&quot;enddate1&quot;,&quot;week&quot;)) %&gt;% 

#group by week of the year
  group_by(week) %&gt;% 
  
# calculate mean, SD, count, SE, lower/upper 95% CI for net approval rate
  summarise(
    mean_NAR = mean(net_approval_rate,na.rm=TRUE),
    sd_NAR = sd(net_approval_rate,na.rm=TRUE),
    count = n(),
    se_NAR = sd_NAR/ sqrt(count),
    t_critical = qt(0.975, count - 1 ),
    lower = mean_NAR - qnorm(0.975) * se_NAR,
    upper = mean_NAR + qnorm(0.975) * se_NAR
  ) 

#print table
mydata2</code></pre>
<pre><code>## # A tibble: 40 × 8
##     week mean_NAR sd_NAR count se_NAR t_critical lower upper
##    &lt;dbl&gt;    &lt;dbl&gt;  &lt;dbl&gt; &lt;int&gt;  &lt;dbl&gt;      &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
##  1     3     18.6   8.23    11   2.48       2.23  13.8  23.5
##  2     4     18.5   8.94    51   1.25       2.01  16.0  20.9
##  3     5     16.7   7.59    54   1.03       2.01  14.7  18.7
##  4     6     16.6   8.16    37   1.34       2.03  14.0  19.3
##  5     7     16.3   7.34    50   1.04       2.01  14.3  18.4
##  6     8     15.0   7.77    50   1.10       2.01  12.8  17.1
##  7     9     13.4   7.46    53   1.02       2.01  11.3  15.4
##  8    10     12.9   7.08    49   1.01       2.01  11.0  14.9
##  9    11     15.8   7.45    43   1.14       2.02  13.5  18.0
## 10    12     14.7   9.32    57   1.23       2.00  12.3  17.2
## # … with 30 more rows</code></pre>
<pre class="r"><code>p &lt;- ggplot(mydata2, aes(x = week, y = mean_NAR)) +
  geom_ribbon(aes(ymin = lower,
                  ymax = upper),
              color = &quot;#FF9999&quot;,
              fill = &quot;grey90&quot;,
              alpha = 0.5) + #add ci to the graph
  geom_point(color = &quot;#FF9999&quot;) +
  geom_line(color = &quot;#FF9999&quot;) +
  geom_smooth(se = F) +
  theme_bw() + #delete background
  xlab(&quot;Week of the Year&quot;) +
  ylab(&quot;Average Approval Margin (approve- disapprove)&quot;) +
  labs(title = &quot;Estimating Approval Margin for Joe Biden&quot;, 
       subtitle = &quot;Weekly average of all polls (week 8-39 of 2021)&quot;) +
  theme(axis.title.x = element_text(face = &quot;bold&quot;),
        axis.title.y = element_text(face = &quot;bold&quot;),
        plot.title = element_text(face = &quot;bold&quot;),
        plot.subtitle = element_text(face = &quot;bold&quot;),
        axis.ticks = element_blank(),
        panel.border = element_blank()) + #delete panel border
  scale_y_continuous(limits = c(-15,30), breaks = seq(-15,10,2.5)) +
  scale_x_continuous(breaks = c(13,26,39)) +
  geom_hline(yintercept = 0, color = &quot;orange&quot;, size = 1.5) + #add y=0 line
  annotate(&quot;text&quot;, x = 23, y = 30, label = &quot;2021&quot;) 

p</code></pre>
<p><img src="/blogs/homework2_website_files/figure-html/unnamed-chunk-5-1.png" width="648" style="display: block; margin: auto;" /></p>
</div>
<div id="compare-confidence-intervals" class="section level2">
<h2>Compare Confidence Intervals</h2>
<p>Compare the confidence intervals for <code>week 3</code> and <code>week 25</code>. Can you explain what’s going on? One paragraph would be enough.</p>
<p><strong>At the time we downloaded (Sep 30), the data starts from Feb 22 (week8), so we just compare week8 and week33, which also show difference between their confidence intervals. Week8 has the smallest sample size(n=33) among all, and the largest SE, while week33 has a sample size of 70 and relatively smaller SE. As the sample size grows, the sample more closely approximates the population. Therefore, we can be more confident in our estimate of the standard error because it more closely approximates the true population standard error, thus we have a much wider confidence intervals of week33, compared to week8.
This could be due to geopolitical considerations such as the Afghanistan situation while on the other hand one could expect the approval rating to be less uncertain a couple of weeks after the new President is in office.</strong></p>
</div>
</div>
<div id="challenge-1-excess-rentals-in-tfl-bike-sharing" class="section level1">
<h1>Challenge 1: Excess rentals in TfL bike sharing</h1>
<p>Recall the TfL data on how many bikes were hired every single day. We can get the latest data by running the following</p>
<pre class="r"><code>url &lt;- &quot;https://data.london.gov.uk/download/number-bicycle-hires/ac29363e-e0cb-47cc-a97a-e216d900a6b0/tfl-daily-cycle-hires.xlsx&quot;

# Download TFL data to temporary file
httr::GET(url, write_disk(bike.temp &lt;- tempfile(fileext = &quot;.xlsx&quot;)))</code></pre>
<pre><code>## Response [https://airdrive-secure.s3-eu-west-1.amazonaws.com/london/dataset/number-bicycle-hires/2021-09-23T12%3A52%3A20/tfl-daily-cycle-hires.xlsx?X-Amz-Algorithm=AWS4-HMAC-SHA256&amp;X-Amz-Credential=AKIAJJDIMAIVZJDICKHA%2F20211019%2Feu-west-1%2Fs3%2Faws4_request&amp;X-Amz-Date=20211019T175050Z&amp;X-Amz-Expires=300&amp;X-Amz-Signature=4ae321b07a114cb825851f5d1f2b533657d34448e823c84999157e20df5a4b78&amp;X-Amz-SignedHeaders=host]
##   Date: 2021-10-19 17:54
##   Status: 200
##   Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
##   Size: 174 kB
## &lt;ON DISK&gt;  /var/folders/83/x2v7d5797vg1ffh2r8wqn6w80000gp/T//RtmpxlLbnn/file3d34600ae86.xlsx</code></pre>
<pre class="r"><code># Use read_excel to read it as dataframe
bike0 &lt;- read_excel(bike.temp,
                   sheet = &quot;Data&quot;,
                   range = cell_cols(&quot;A:B&quot;))

# change dates to get year, month, and week
bike &lt;- bike0 %&gt;% 
  clean_names() %&gt;% 
  rename (bikes_hired = number_of_bicycle_hires) %&gt;% 
  mutate (year = year(day),
          month = lubridate::month(day, label = TRUE),
          week = isoweek(day))</code></pre>
<p>We can easily create a facet grid that plots bikes hired by month and year.</p>
<p><img src="/Users/nohadmessimortada/Desktop/my_website/images/tfl_distributions_monthly.png" width="100%" style="display: block; margin: auto;" /></p>
<p>Look at May and Jun and compare 2020 with the previous years. What’s happening?</p>
<p><strong>Historically, as the weather improves in May we see an increase in number of bikes rented compared to April. Because of the pandemic and the consequent lockdown, this number didn’t pick up in the Spring of 2020 as most people were working from home. </strong></p>
<p>However, the challenge I want you to work on is to reproduce the following two graphs.</p>
<p><img src="/Users/nohadmessimortada/Desktop/my_website/images/tfl_monthly.png" width="100%" style="display: block; margin: auto;" /></p>
<p><img src="/blogs/homework2_website_files/figure-html/unnamed-chunk-6-1.png" width="1920" style="display: block; margin: auto;" /></p>
<p>The second one looks at percentage changes from the expected level of weekly rentals. The two grey shaded rectangles correspond to Q2 (weeks 14-26) and Q4 (weeks 40-52).</p>
<p><img src="/Users/nohadmessimortada/Desktop/my_website/images/tfl_weekly.png" width="100%" style="display: block; margin: auto;" /></p>
<pre class="r"><code>library(scales)
bike.3 &lt;- bike %&gt;% filter(year &gt;= 2016 &amp; year &lt;= 2021) %&gt;% group_by(year, week) %&gt;% summarise(bikes_hired = mean(bikes_hired))
bike.3[(nrow(bike.3)),]$week &lt;- 36
bike.4 &lt;- bike %&gt;% filter(year &gt;= 2016 &amp; year &lt; 2019) %&gt;% group_by(week) %&gt;% summarise(bikes_hired = mean(bikes_hired))
bike.3$rate &lt;- 0
for(i in 1:nrow(bike.4)){
  bike.3 &lt;- bike.3 %&gt;% mutate(rate=ifelse(week==i, (bikes_hired - bike.4$bikes_hired[i])/bike.4$bikes_hired[i], rate))
}
bike.3$upper &lt;- ifelse(bike.3$rate &gt; 0, bike.3$rate, 0)
bike.3$lower &lt;- ifelse(bike.3$rate &gt; 0, 0, bike.3$rate)

ggplot(data=bike.3, aes(as.numeric(week))) +
  geom_ribbon(aes(ymin=0, ymax=upper), fill=&quot;#99FF99&quot;) +
  geom_ribbon(aes(ymin=lower, ymax=0), fill=&quot;#FF9999&quot;) +
  geom_line(aes(y=rate),color = &#39;#000000&#39;, size = 0.2) +
  geom_rug(sides=&quot;b&quot;,mapping=aes(x=ifelse(rate &gt; 0,week,NA)), colour = &quot;#99FF99&quot;) +
  geom_rug(sides=&quot;b&quot;,mapping=aes(x=ifelse(rate &lt; 0,week,NA)), colour = &quot;#FF9999&quot;) +
  facet_wrap( ~ year,nrow=2) + 
  labs(title = &quot;Monthly changes in TfL bike rentals&quot;, subtitle = &quot;% Change from monthly average \n calculated between 2016-2019&quot;, caption = &quot;Source: TfL, London Data Store&quot;) +
  geom_rect(xmin=13, xmax=26, ymin=-1, ymax=1, colour = &quot;#CCCCCC&quot;, alpha=0.003) + 
  geom_rect(xmin=39, xmax=53, ymin=-1, ymax=1, colour = &quot;#CCCCCC&quot;, alpha=0.003) + 
  scale_x_discrete(name = &quot;Week&quot;) +
  scale_y_continuous(labels = percent) +
  theme(panel.border = element_blank(),
        text = element_text(size = 8),
        panel.background = element_blank(),
        panel.grid = element_line(color = &quot;#999999&quot;,
                                  size = 0.2,
                                  linetype = 1),
        strip.background = element_blank(),
        axis.title.y=element_blank())</code></pre>
<p><img src="/blogs/homework2_website_files/figure-html/unnamed-chunk-7-1.png" width="1440" style="display: block; margin: auto;" /></p>
<p>For both of these graphs, you have to calculate the expected number of rentals per week or month between 2016-2019 and then, see how each week/month of 2020-2021 compares to the expected rentals. Think of the calculation <code>excess_rentals = actual_rentals - expected_rentals</code>.</p>
<p>Should you use the mean or the median to calculate your expected rentals? Why?</p>
<p><strong>The median is a good alternative to the mean in terms of “expected number” typically when the data has several outliers or the skewness is considerably high. In this case, the expected number of rentals per week is better expressed by the mean, since one expects a cyclical behaviour in the number of hires by week.</strong></p>
<p>In creating your plots, you may find these links useful:</p>
<ul>
<li><a href="https://ggplot2.tidyverse.org/reference/geom_ribbon.html" class="uri">https://ggplot2.tidyverse.org/reference/geom_ribbon.html</a></li>
<li><a href="https://ggplot2.tidyverse.org/reference/geom_tile.html" class="uri">https://ggplot2.tidyverse.org/reference/geom_tile.html</a></li>
<li><a href="https://ggplot2.tidyverse.org/reference/geom_rug.html" class="uri">https://ggplot2.tidyverse.org/reference/geom_rug.html</a></li>
</ul>
</div>
<div id="challenge-2-how-has-the-cpi-and-its-components-changed-over-the-last-few-years" class="section level1">
<h1>Challenge 2: How has the CPI and its components changed over the last few years?</h1>
<p>Remember how we used the tidyqant package to download CPI data. In this exercise, I would like you to do the following:</p>
<ol style="list-style-type: decimal">
<li>You can find <a href="https://fredaccount.stlouisfed.org/public/datalist/843">CPI components at FRED</a>. You should adapt the code from German polls to scrape the FRED website and pull all of the CPI components into a vector. FIY, the list of components is the second table in that webpage.</li>
<li>Once you have a vector of components, you can then pass it to <code>tidyquant::tq_get(get = "economic.data", from =  "2000-01-01")</code> to get all data since January 1, 2000</li>
<li>Since the data you download is an index with various starting dates, you need to calculate the yearly, or 12-month change. To do this you need to use the <code>lag</code> function, and specifically, <code>year_change = value/lag(value, 12) - 1</code>; this means you are comparing the current month’s value with that 12 months ago lag(value, 12).</li>
<li>I want you to order components so the higher the yearly change, the earlier does that component appear.</li>
<li>You should also make sure that the <strong>All Items</strong> CPI (CPIAUCSL) appears first.</li>
<li>Add a <code>geom_smooth()</code> for each component to get a sense of the overall trend. 1 You may want to colour the points according to whether yearly change was positive or negative.</li>
</ol>
<p>Having done this, you should get this graph.</p>
<p><img src="/Users/nohadmessimortada/Desktop/my_website/images/cpi_components_since_2016.png" width="100%" style="display: block; margin: auto;" /></p>
<pre class="r"><code>library(leaps)
library(lubridate)
library(rvest)
url &lt;- &quot;https://fredaccount.stlouisfed.org/public/datalist/843&quot;
webpage &lt;- read_html(url)
tr &lt;- html_nodes(webpage, &#39;tr&#39;)
ans &lt;- html_text(tr)
title &lt;- c()
series_id &lt;- c()
for(i in 3:51){
  tmp &lt;- strsplit(ans[i], split=&quot;\n&quot;)
  n_last &lt;- nchar(tmp[[1]][2])
  title &lt;- append(title, substr(tmp[[1]][2], 71, n_last-21))
  n_last &lt;- nchar(tmp[[1]][5])
  series_id &lt;- append(series_id, substr(tmp[[1]][5],9,n_last))
}
title[2:5] &lt;- title[1:4]
title[1] &lt;- &quot;All Items&quot;

df &lt;- tidyquant::tq_get(series_id, get=&quot;economic.data&quot;, from=&quot;2000-01-01&quot;)
#load(&quot;/Users/guidobassi/Desktop/ca09.mfa2022/session04_workshop2/df&quot;)
data &lt;- rbind(df %&gt;% filter(symbol==&quot;CPIAUCSL&quot;)  ,df %&gt;% filter(symbol!=&quot;CPIAUCSL&quot;)) %&gt;%
  mutate(yoy_change = price / lag(price, 12) - 1)
  
data$title &lt;- &quot;&quot;
k &lt;- 1
for(i in 1:nrow(data)){
  if(i==1){
    data$title[i] &lt;- title[k]
  }
  else{
    if(data$symbol[i] != data$symbol[i-1]){
      k &lt;- k + 1
      data$title[i] &lt;- title[k]
    }
    else{
      data$title[i] &lt;- title[k]
    }
  }
}

data_1 &lt;- data %&gt;% filter(date &gt;= &quot;2016-01-01&quot;) %&gt;% 
  filter(date &lt;= &quot;2021-08-01&quot;) # filtering the data so that we only have data for the period Jan 2016 - Aug 2021
list_cpi_max &lt;- aggregate(data_1[,4], list(data_1$title), max) # creating a list with the max yoy change per title
list_cpi_max_ordered &lt;- arrange(list_cpi_max, desc(yoy_change)) # ordering our list in descending order
order_0 &lt;- list_cpi_max_ordered[1:49, 1] # extracting the order our graphs will be in from the list
new_order &lt;- order_0[c(24,1:23,25:length(order_0))] # adjusting the order to have &quot;all items&quot; first



geom_line(aes(y=rate),color = &#39;#000000&#39;, size = 0.2)</code></pre>
<pre><code>## mapping: y = ~rate 
## geom_line: na.rm = FALSE, orientation = NA
## stat_identity: na.rm = FALSE
## position_identity</code></pre>
<pre class="r"><code>data_2 &lt;- data_1 %&gt;% group_by(title) 
data$title &lt;- factor(data$title, levels = title)

ggplot(data_2 %&gt;% filter(year(date) &gt;= 2016), aes(date, yoy_change)) + 
  geom_point(aes(colour = (price/lag(price,12) -1) &lt; 0), size=1.5) + 
  geom_smooth(method=&quot;loess&quot;, formula = y ~ x, size=1.5, se = FALSE, colour = &quot;grey&quot;) + 
  facet_wrap( ~ factor(title, levels = new_order),nrow=7,scales = &quot;free&quot;) + 
  scale_y_continuous(name = &quot;YoY % Change&quot;, labels = percent) +
  labs(title = &quot;Yearly change of US CPI (All Items) and its components&quot;, 
       subtitle = &quot;YoY change being positive or negative \n Jan 2016 to Aug 2021&quot;, 
       caption = &quot;Data from St. Louls Fed FRED \n https://fredaccount.stlouisfed.org/public/datalist/843&quot;) +
  theme(text = element_text(size = 7),
        legend.position = &quot;none&quot;,
        axis.title.x=element_blank(),
        strip.text = element_text(size = 10),
      axis.text = element_text(size = 9),
      plot.title = element_text(size = 15),
      plot.subtitle = element_text(size = 12),
      axis.title = element_text(size = 12),
      plot.caption = element_text(size = 10))</code></pre>
<p><img src="/blogs/homework2_website_files/figure-html/unnamed-chunk-8-1.png" width="1920" style="display: block; margin: auto;" /></p>
<p>This graphs is fine, but perhaps has too many sub-categories. You can find the <a href="https://www.bls.gov/cpi/tables/relative-importance/2020.htm">relative importance of components in the Consumer Price Indexes: U.S. city average, December 2020</a> here. Can you choose a smaller subset of the components you have and only list the major categories (Housing, Transportation, Food and beverages, Medical care, Education and communication, Recreation, and Apparel), sorted according to their relative importance?</p>
<p><strong>Interestingly, we see how inflation is driven by certain categories of products such as used cars, gasoline or motor fuel which are very much correlated with industries that suffered the most during the pandemic and so picked up quite substantially thereafter.</strong></p>
<pre class="r"><code>url_new &lt;- &quot;https://www.bls.gov/cpi/tables/relative-importance/2020.htm&quot;

# importing data relative to the importance of cpi components
# https://www.rdocumentation.org/packages/rvest/versions/0.3.6/topics/html_nodes
# https://www.rdocumentation.org/packages/textreadr/versions/1.0.2/topics/read_html
tables_new &lt;- url_new %&gt;%
  read_html() %&gt;% 
  html_nodes(css=&quot;table&quot;)

tables_new1 &lt;- map(tables_new, . %&gt;% 
             html_table()%&gt;% 
             clean_names())

# ranking CPI components using slice
cpi_importance &lt;- tables_new1[[1]] %&gt;%
  slice(2:n()) %&gt;%
  subset(item_and_group ==&quot;Transportation&quot;|item_and_group ==&quot;Food and beverages&quot;|item_and_group ==&quot;Medical care&quot;|item_and_group ==&quot;Education and communication&quot;|item_and_group ==&quot;Recreation&quot;|item_and_group ==&quot;Apparel&quot; | item_and_group == &quot;Housing&quot;) %&gt;%
  mutate(across(where(is.character), str_trim)) %&gt;%
  transform(u_s_city_average = as.numeric(u_s_city_average)) %&gt;%
  arrange(desc(u_s_city_average)) 

# selecting a subset of components of the cpi basket
components &lt;- data_2 %&gt;%
  subset(title  == &quot;Transportation&quot;|title  == &quot;Food and Beverages&quot;| title == &quot;Housing&quot;)

# The function factor is used to encode a vector as a factor in the variable title: the levels are given by the cpi components previously selected
components$title  = factor(components$title , levels = c(&quot;Transportation&quot;,&quot;Food and Beverages&quot;,&quot;Housing&quot;))


components %&gt;%
  ggplot(aes(x = date, y = yoy_change, group = title )) +
  facet_wrap(.~components$title , ncol=2)+
  geom_point(aes(color = factor(sign(yoy_change))))+
  geom_smooth(aes(color = &quot;black&quot;))+
  theme_bw()+
  theme(legend.position=&quot;none&quot;)+
  labs(title = &quot;Subset of CPI components&quot;, x = &quot;year&quot;, y = &quot;yoy change&quot;)</code></pre>
<p><img src="/blogs/homework2_website_files/figure-html/unnamed-chunk-9-1.png" width="648" style="display: block; margin: auto;" /></p>
</div>
<div id="deliverables" class="section level1">
<h1>Deliverables</h1>
<p>As usual, there is a lot of explanatory text, comments, etc. You do not need these, so delete them and produce a stand-alone document that you could share with someone. Knit the edited and completed R Markdown file as an HTML document (use the “Knit” button at the top of the script editor window) and upload it to Canvas.</p>
</div>
<div id="details" class="section level1">
<h1>Details</h1>
<ul>
<li>Who did you collaborate with: Group B11</li>
<li>Approximately how much time did you spend on this problem set: 1 day</li>
<li>What, if anything, gave you the most trouble: NA</li>
</ul>
<p><strong>Please seek out help when you need it,</strong> and remember the <a href="https://mam202.netlify.app/syllabus/#the-15-minute-rule" target="_blank">15-minute rule</a>. You know enough R (and have enough examples of code from class and your readings) to be able to do this. If you get stuck, ask for help from others, post a question on Slack– and remember that I am here to help too!</p>
<blockquote>
<p>As a true test to yourself, do you understand the code you submitted and are you able to explain it to someone else?</p>
</blockquote>
</div>
<div id="rubric" class="section level1">
<h1>Rubric</h1>
<p>Check minus (1/5): Displays minimal effort. Doesn’t complete all components. Code is poorly written and not documented. Uses the same type of plot for each graph, or doesn’t use plots appropriate for the variables being analyzed.</p>
<p>Check (3/5): Solid effort. Hits all the elements. No clear mistakes. Easy to follow (both the code and the output).</p>
<p>Check plus (5/5): Finished all components of the assignment correctly and addressed both challenges. Code is well-documented (both self-documented and with additional comments as necessary). Used tidyverse, instead of base R. Graphs and tables are properly labelled. Analysis is clear and easy to follow, either because graphs are labeled clearly or you’ve written additional text to describe how you interpret the output.</p>
</div>
